describe("Register", function() {
    beforeEach(function() {
       cy.task("resetDb")
       cy.visit('/register')
    })
    it('check layout', function(){
        cy.get('#title').contains('Register')
        cy.get('#login')
        cy.get('#register')
    })
    it('check invalid name redirects', function(){
        cy.get('#username').type('testuser2')
        cy.get('#password').type('testpassword2')
        cy.get('#name').type('test user 2')
        cy.get('#email').type('test2@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Name can only contain letters')

    })
    it('check empty name redirects', function(){
        cy.get('#username').type('testuser2')
        cy.get('#password').type('testpassword2')
        cy.get('#email').type('test2@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Please enter a name')
    })
    it('check invalid password redirects', function(){
        cy.get('#username').type('testuser2')
        cy.get('#password').type('test')
        cy.get('#name').type('test user two')
        cy.get('#email').type('test2@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Password length must be between 5 and 20 charachters')
    })
    it('check invalid email redirects', function(){
        cy.get('#username').type('testuser2')
        cy.get('#password').type('testpassword2')
        cy.get('#name').type('test user two')
        cy.get('#email').type('test2@test')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Invalid email address')
    })
    it('check taken email redirects', function(){
        cy.task('createUser')
        cy.get('#username').type('testuser2')
        cy.get('#password').type('testpassword2')
        cy.get('#name').type('test user')
        cy.get('#email').type('testuser1@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Email address already in use')
    })
    it('check taken username redirects', function(){
        cy.task('createUser')
        cy.get('#username').type('testuser1')
        cy.get('#password').type('testpassword2')
        cy.get('#name').type('test user two')
        cy.get('#email').type('test2@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Username address already in use')
    })
    it('check invalid username redirects', function(){
        cy.get('#password').type('testpassword2')
        cy.get('#email').type('test2@test.com')
        cy.get('#name').type('test user two')
        cy.get('#username').type('test')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Username must be five charachters')
    })
    it('passing test', function(){
        cy.get('#password').type('testpassword2')
        cy.get('#email').type('test2@test.com')
        cy.get('#name').type('test user two')
        cy.get('#username').type('testuser2')
        cy.get('#submit').click()
        cy.url().should('not.contain', 'register')
    })
})
    