describe("Register", function() {
    beforeEach(function() {
       cy.task("resetDb")
       cy.task("createUser")
       cy.visit('/register')
    })
    xit('check invalid name redirects', function(){
        cy.get('#username').type('test man one')
        cy.get('#password').type('testpassword1')
        cy.get('#name').type('test man 1')
        cy.get('#email').type('test1@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Name can only contain letters')

    })
    xit('check empty name redirects', function(){
        cy.get('#username').type('testman2')
        cy.get('#password').type('testpassword2')
        cy.get('#email').type('test2@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Please enter a name')
    })
    xit('check invalid password redirects', function(){
        cy.get('#username').type('testman3')
        cy.get('#password').type('test')
        cy.get('#name').type('test man three')
        cy.get('#email').type('test3@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Password length must be between 5 and 20 charachters')
    })
    xit('check invalid email redirects', function(){
        cy.get('#username').type('testman5')
        cy.get('#password').type('testpassword5')
        cy.get('#name').type('test man five')
        cy.get('#email').type('test5@test')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Invalid email address')
    })
    xit('check taken email redirects', function(){
        cy.get('#username').type('testman6')
        cy.get('#password').type('testpassword6')
        cy.get('#name').type('test man six')
        cy.get('#email').type('seededtest@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Email address already in use')
    })
    xit('check taken username redirects', function(){
        cy.get('#username').type('seededtestman1')
        cy.get('#password').type('testpassword7')
        cy.get('#name').type('test man seven')
        cy.get('#email').type('test7@test.com')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Username address already in use')
    })
    xit('check empty username redirects', function(){
        cy.get('#password').type('testpassword8')
        cy.get('#email').type('test9@test.com')
        cy.get('#name').type('test man eight')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Please enter a username')
    })
    xit('passing test', function(){
        cy.get('#password').type('testpassword10')
        cy.get('#email').type('test10@test.com')
        cy.get('#name').type('test man ten')
        cy.get('#username').type('testman10')
        cy.get('#submit').click()
        cy.get('#register')
    })
    it('check username is 5 charachters long', function(){
        cy.get('#password').type('testpassword11')
        cy.get('#email').type('test11@test.com')
        cy.get('#name').type('test man eleven')
        cy.get('#username').type('test')
        cy.get('#submit').click()
        cy.url().should('contain', '/register')
        cy.get('#errors').contains('Username must be five charachters')
    })
})
    