describe("Check replies as testuser1", function() {
    beforeEach(function() {
      cy.task('resetDb')
      cy.task('createReply')
      cy.visit('/login')
      cy.get('#email').type('testuser1@test.com')
      cy.get('#password').type('testpassword1')
      cy.get('#submit').click()
    })
    it('check replies displayed', function(){
       cy.get('#tweet-0').contains('test tweet 1')  
       cy.get('#tweet-0-reply-0').contains('test reply 1')
       cy.get('#tweet-0-reply-0-timestamp').contains('10:50 12-10-1995')
       cy.get('#tweet-0-reply-0-edit').should('not.exist')
       cy.get('#tweet-0-reply-0-delete').should('not.exist')
    })
    it('check replies can be added', function(){
       cy.get('#tweet-1-reply').click()
       cy.url().should('contain', '/reply')
       cy.get('#reply-text').type('test reply 2')
       cy.get('#save').click()
       cy.get('#tweet-1-reply-0').contains('test reply 2')
       cy.get('#tweet-0-div').should('not.contain', 'test reply 2')
    })
})
describe("Check replies as testuser2", function() {
      beforeEach(function() {
        cy.task('resetDb')
        cy.task('createReply')
        cy.visit('/login')
        cy.get('#email').type('testuser2@test.com')
        cy.get('#password').type('testpassword2')
        cy.get('#submit').click()
      })
      it('check replies displayed', function(){
         cy.get('#tweet-0').contains('test tweet 1')  
         cy.get('#tweet-0-reply-0').contains('test reply 1')
         cy.get('#tweet-0-reply-0-timestamp').contains('10:50 12-10-1995')
         cy.get('#tweet-0-reply-0-edit')
         cy.get('#tweet-0-reply-0-delete')
      })
      it('check reply can be deleted', function (){
         cy.get('#tweet-0-reply-0-delete').click()
         cy.url().should('contain','/tweet')
         cy.get('#tweet-0-reply-0').should('not.exist')
      })
      it('check reply can be edited', function(){
         cy.get('#tweet-0-reply-0-edit').click()
         cy.url().should('contain','/reply')
         cy.get('#edit-reply-text').type('edited reply')
         cy.get('#save').click()
         cy.url().should('contain', '/tweet')
         cy.get('#tweet-0-reply-0').contains('edited reply')
         cy.get('#tweet-1-div').should('not.contain', 'edited reply')
      })
})