describe("Check replies as testuser1", function() {
    beforeEach(function() {
      cy.task('resetDb')
      cy.task('createReply')
      cy.visit('/login')
      cy.get('#email').type('testuser1@test.com')
      cy.get('#password').type('testpassword1')
      cy.get('#submit').click()
    })
    it('check replies displayed', function(){
       cy.get('#tweet-0').contains('test tweet 2')  
       cy.get('#tweet-0-reply-0').contains('test reply to tweet 2')
       cy.get('#tweet-0-reply-0-timestamp').contains('11:30 12-10-1995')
       cy.get('#tweet-0-reply-0-username').contains('testuser1')
       cy.get('#tweet-0-reply-0-edit')
       cy.get('#tweet-0-reply-0-delete')
       cy.get('#tweet-1').contains('test tweet 1')  
       cy.get('#tweet-1-reply-0').contains('test reply to tweet 1')
       cy.get('#tweet-1-reply-0-timestamp').contains('12:0 12-10-1995')
       cy.get('#tweet-1-reply-0-username').contains('testuser2')
       cy.get('#tweet-1-reply-0-edit').should('not.exist')
       cy.get('#tweet-1-reply-0-delete').should('not.exist')
    })
    it('check replies can be added', function(){
       cy.get('#tweet-0').contains('test tweet 2')
       cy.get('#tweet-0-reply').click()
       cy.get('#reply-text').type('test reply 2')
       cy.get('#save').click()
       cy.get('#tweet-0-reply-0').contains('test reply 2')
       cy.get('#tweet-1-div').should('not.contain', 'test reply 2')
    })
    it('check reply can be deleted', function (){
       cy.get('#tweet-0-reply-0').contains('test reply to tweet 2')
       cy.get('#tweet-0-reply-0-delete').click()
       cy.get('#title').contains('Peep Timeline')
       cy.get('#tweet-0-reply-0').should('not.exist')
       cy.get('#tweet-1-reply-0').contains('test reply to tweet 1')
      })
   it('check reply can be edited', function(){
      cy.get('#tweet-0-reply-0').contains('test reply to tweet 2')
      cy.get('#tweet-0-reply-0-edit').click()
      cy.get('#edit-reply-text').type('edited reply')
      cy.get('#save').click()
      cy.get('#title').contains('Peep Timeline')
      cy.get('#tweet-0-reply-0').contains('edited reply')
      cy.get('#tweet-1-reply-0').contains('test reply to tweet 1')   
   })
})