describe("check tweet page", function() {
    beforeEach(function() {
      cy.task('resetDb')
      cy.task('createTweet')
      cy.visit('/login')
      cy.get('#email').type('testuser1@test.com')
      cy.get('#password').type('testpassword1')
      cy.get('#submit').click()
    })
    it('check order, info and layout', function(){
        cy.get('#title').contains('Peep Timeline')
        cy.get('#tweet-0').contains('test tweet 2')
        cy.get('#tweet-0-delete').should('not.exist')
        cy.get('#tweet-0-reply')
        cy.get('#tweet-0-edit').should('not.exist')
        cy.get('#tweet-0-timestamp').contains('11:0 12-10-1995')
        cy.get('#tweet-0-username').contains('testuser2')
        cy.get('#tweet-1-delete')
        cy.get('#tweet-1-edit')
        cy.get('#tweet-1-reply')
        cy.get('#tweet-1-timestamp').contains('10:0 12-10-1995')
        cy.get('#tweet-1-username').contains('testuser1')
    })
    it('check new tweet button', function(){
        cy.get('#tweet-text').type('test tweet 3')
        cy.get('#save').click()
        cy.get('#tweet-0').contains('test tweet 3')
        cy.get('#tweet-0-username').contains('testuser1')
        cy.get('#tweet-1').contains('test tweet 2')
        cy.get('#tweet-1-username').contains('testuser2')
        cy.get('#tweet-2').contains('test tweet 1')
        cy.get('#tweet-2-username').contains('testuser1')
        
    })
    it('check delete button', function(){
        cy.get('#tweet-1').contains('test tweet 1')
        cy.get('#tweet-1-delete').click()
        cy.get('#title').contains('Peep Timeline')
        cy.get('#tweet-1').should('not.exist')
        cy.get('#tweet-0').contains('test tweet 2')
        cy.get('#tweet-0-username').contains('testuser2')
    })
    it('check edit button', function(){
        cy.get('#tweet-1').contains('test tweet 1')
        cy.get('#tweet-1-edit').click()
        cy.get('#edit-text').type('edited test tweet')
        cy.get('#save').click()
        cy.get('#tweet-1').contains('edited test tweet')
        cy.get('#tweet-1-username').contains('testuser1')
        cy.get('#tweet-0').contains('test tweet 2')
        cy.get('#tweet-0-username').contains('testuser2')
    })
})