describe("Check tweet page as testuser1", function() {
    beforeEach(function() {
      cy.task('resetDb')
      cy.task('createTweet')
      cy.visit('/login')
      cy.get('#email').type('testuser1@test.com')
      cy.get('#password').type('testpassword1')
      cy.get('#submit').click()

    })
    it('Check date and layout', function(){
        cy.get('#tweet-0').contains('test tweet 1')
        cy.get('#tweet-0-delete')
        cy.get('#tweet-0-edit')
        cy.get('#tweet-0-reply')
        cy.get('#tweet-0-timestamp').contains('10:30 12-10-1995')
    })
    it('Check new tweet correctly displayed', function(){
        cy.get('#tweet-text').type('test tweet 2')
        cy.get('#save').click()
        cy.url().should('contain', '/tweet')
        cy.get('#tweet-1').contains('test tweet 2')
    })
    it('check tweet correctly deleted', function(){
        cy.get('#tweet-0').contains('test tweet 1')
        cy.get('#tweet-0-delete').click()
        cy.get('#tweet-0').should('not.exist')
        cy.url().should('contain', '/tweet')
    })
    it('check edit works correctly', function(){
        cy.get('#tweet-0').contains('test tweet 1')
        cy.get('#tweet-0-edit').click()
        cy.get('#edit-text').type('edited test tweet')
        cy.get('#save').click()
        cy.get('#tweet-0').contains('edited test tweet')
    })
})
describe('check tweet page as testuser2', function(){
    it('check edit and delete buttons are not present to a user who did not write the tweet', function(){
      cy.task('resetDb')
      cy.task('createUser')
      cy.task('createTweet')
      cy.visit('/login')
      cy.get('#email').type('testuser2@test.com')
      cy.get('#password').type('testpassword2')
      cy.get('#submit').click()
      cy.url().should('contain', '/tweet')
      cy.get('#tweet-0-edit').should('not.exist') 
      cy.get('#tweet-0-delete').should('not.exist') 
    })
})